(eval-when-compile    (require 'color-theme))
(defun color-theme-mlp ()
  "Color theme by Matt Patey, created 2011-01-10."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#1e1e1e")
      (background-mode . dark)
      (border-color . "#111")
      (cursor-color . "#ffdd33")
      (foreground-color . "#e4e4ef")
      (mouse-color . "#ffdd33"))
     ((hl-line-face . hl-line)
      (info-lookup-highlight-face . match)
      (ispell-highlight-face . isearch)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#181818" :foreground "#e4e4ef" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "microsoft" :family "Consolas"))))
     (better-fringes-bitmap ((t (:foreground "dark khaki"))))
     (better-fringes-important-bitmap ((t (:foreground "red"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "#95a99f"))))
     (border ((t (:background "#111" :foreground "#444"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (compilation-column-number ((t (:foreground "#95a99f"))))
     (compilation-error ((t (:foreground "#f43841"))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:foreground "#f4f4ff"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:family "Consolas" :foundry "microsoft" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#e4e4ef" :background "#181818" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "#ffdd33"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "#96A6C8"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "#96A6C8" :height 0.8))))
     (dired-directory ((t (:foreground "#96a6c8"))))
     (dired-flagged ((t (:foreground "#f43841"))))
     (dired-header ((t (:foreground "#95a99f"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "#95a99f"))))
     (dired-marked ((t (:foreground "#f43841"))))
     (dired-perm-write ((t (:foreground "#cc8c3c"))))
     (dired-symlink ((t (:foreground "#ffdd33"))))
     (dired-warning ((t (:foreground "#f43841"))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (elscreen-tab-background-face ((t (:background "Gray50"))))
     (elscreen-tab-control-face ((t (:background "white" :foreground "black" :underline "Gray50"))))
     (elscreen-tab-current-screen-face ((t (:background "white" :foreground "black"))))
     (elscreen-tab-other-screen-face ((t (:background "Gray85" :foreground "Gray50"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:foreground "#ff9999"))))
     (flymake-warnline ((t (:italic t :slant italic))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (:bold t :foreground "#95a99f" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "#95a99f" :slant italic))))
     (font-latex-math-face ((t (:foreground "#73c936"))))
     (font-latex-sectioning-5-face ((t (:bold t :foreground "#96a6c8" :weight bold))))
     (font-latex-slide-title-face ((t (:foreground "#96a6c8"))))
     (font-latex-string-face ((t (:foreground "#73c936"))))
     (font-latex-warning-face ((t (:foreground "#f43841"))))
     (font-lock-builtin-face ((t (:foreground "#ffdd33"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#cc8c3c"))))
     (font-lock-comment-face ((t (:foreground "#cc8c3c"))))
     (font-lock-constant-face ((t (:foreground "#95a99f"))))
     (font-lock-doc-face ((t (:foreground "#73c936"))))
     (font-lock-doc-string-face ((t (:foreground "#73c936"))))
     (font-lock-function-name-face ((t (:foreground "#96a6c8"))))
     (font-lock-keyword-face ((t (:foreground "#ffdd33"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "#95a99f"))))
     (font-lock-reference-face ((t (:foreground "#95a99f"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "#73c936"))))
     (font-lock-type-face ((t (:foreground "#95a99f"))))
     (font-lock-variable-name-face ((t (:foreground "#f4f4ff"))))
     (font-lock-warning-face ((t (:foreground "#f43841"))))
     (fringe ((t (:background "#111" :foreground "#444"))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil :height 0.8))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-mumamo-black-b ((t (:bold t :underline t :weight bold))))
     (hi-mumamo-blue ((t (:underline "light blue"))))
     (hi-mumamo-blue-b ((t (:bold t :underline "blue1" :weight bold))))
     (hi-mumamo-green ((t (:underline "green1"))))
     (hi-mumamo-green-b ((t (:bold t :underline "green1" :weight bold))))
     (hi-mumamo-pink ((t (:underline "pink"))))
     (hi-mumamo-red-b ((t (:bold t :underline "red1" :weight bold))))
     (hi-mumamo-yellow ((t (:underline "yellow1"))))
     (highlight ((t (:background "#282828"))))
     (highlight-current-line-face ((t (:background "#282828"))))
     (hl-line ((t (:background "#282828"))))
     (holiday-face ((t (:foreground "#f43841"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:foreground "#f43841"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "white"))))
     (info-header-xref ((t (:foreground "#96a6c8"))))
     (info-menu-header ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :family "Sans Serif" :height 1.728))))
     (info-title-2 ((t (:bold t :family "Sans Serif" :weight bold :height 1.44))))
     (info-title-3 ((t (:bold t :weight bold :family "Sans Serif" :height 1.2))))
     (info-title-4 ((t (:bold t :family "Sans Serif" :weight bold))))
     (info-visited ((t (:foreground "#9e95c7"))))
     (info-xref ((t (:foreground "#96a6c8"))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "#f5f5f5" :foreground "#000"))))
     (isearch-fail ((t (:background "#f43841" :foreground "#000"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "#5f627f" :foreground "#f4f4ff"))))
     (link ((t (:foreground "#96A6C8" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (minibuffer-prompt ((t (:background "#774477" :foreground "#ffff44" :height 0.8))))
     (mlinks-font-lock-face ((t (:underline t :foreground "#96A6C8"))))
     (mlinks-hyperactive-link-face ((t (:foreground "#000" :background "#f5f5f5"))))
     (mlinks-link-face ((t (:background "#282828"))))
     (mode-line ((t (:background "#558800" :foreground "#ffffff" :height 0.8))))
     (mode-line-buffer-id ((t (:bold t :background "#ffffff" :weight bold :height 1.3))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#111111" :foreground "#333333" :height 0.8))))
     (mouse ((t (:background "#ffdd33"))))
     (mumamo-background-chunk-major ((t (nil))))
     (mumamo-background-chunk-submode1 ((t (nil))))
     (mumamo-background-chunk-submode2 ((t (:background "dark green"))))
     (mumamo-background-chunk-submode3 ((t (:background "dark green"))))
     (mumamo-background-chunk-submode4 ((t (:background "dark green"))))
     (mumamo-border-face-in ((t (:italic t :bold t :foreground "#95a99f" :underline t :slant italic :weight bold))))
     (mumamo-border-face-out ((t (:italic t :bold t :foreground "#95a99f" :underline t :slant italic :weight bold))))
     (next-error ((t (nil))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "#f4f4ff"))))
     (nxml-attribute-prefix ((t (:foreground "#ffdd33"))))
     (nxml-attribute-value ((t (:foreground "#73c936"))))
     (nxml-attribute-value-delimiter ((t (:foreground "#73c936"))))
     (nxml-cdata-section-CDATA ((t (:foreground "#ffdd33"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "#95a99f"))))
     (nxml-char-ref-number ((t (:foreground "#95a99f"))))
     (nxml-comment-content ((t (:foreground "#cc8c3c"))))
     (nxml-comment-delimiter ((t (:foreground "#cc8c3c"))))
     (nxml-delimited-data ((t (:foreground "#73c936"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "#96a6c8"))))
     (nxml-element-prefix ((t (:foreground "#ffdd33"))))
     (nxml-entity-ref-delimiter ((t (:foreground "#95a99f"))))
     (nxml-entity-ref-name ((t (:foreground "#95a99f"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal :foundry "misc" :family "fixed"))))
     (nxml-hash ((t (:foreground "#ffdd33"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "#ffdd33"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "#f4f4ff"))))
     (nxml-namespace-attribute-value ((t (:foreground "#73c936"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "#73c936"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "#ffdd33"))))
     (nxml-outline-active-indicator ((t (:stipple nil :background "#181818" :foreground "#e4e4ef" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "microsoft" :family "Consolas" :box 1 :height 98))))
     (nxml-outline-ellipsis ((t (:bold t :family "Consolas" :foundry "microsoft" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#e4e4ef" :background "#181818" :stipple nil :weight bold :height 98))))
     (nxml-outline-indicator ((t (:family "Consolas" :foundry "microsoft" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#e4e4ef" :background "#181818" :stipple nil :height 98))))
     (nxml-processing-instruction-content ((t (:foreground "#73c936"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "#ffdd33"))))
     (nxml-prolog-keyword ((t (:foreground "#ffdd33"))))
     (nxml-prolog-literal-content ((t (:foreground "#73c936"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "#73c936"))))
     (nxml-ref ((t (:foreground "#95a99f"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (org-agenda-column-dateline ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "grey30" :height 120))))
     (org-agenda-date ((t (nil))))
     (org-agenda-date-weekend ((t (:bold t :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 120 :family "DejaVu Sans Mono"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "black"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:foreground "#96a6c8"))))
     (org-level-2 ((t (:foreground "#f4f4ff"))))
     (org-level-3 ((t (:foreground "#ffdd33"))))
     (org-level-4 ((t (:foreground "#cc8c3c"))))
     (org-level-5 ((t (:foreground "#95a99f"))))
     (org-level-6 ((t (:foreground "#95a99f"))))
     (org-level-7 ((t (:foreground "#ffdd33"))))
     (org-level-8 ((t (:foreground "#73c936"))))
     (org-link ((t (:foreground "Cyan" :underline t))))
     (org-property-value ((t (nil))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "LightSalmon"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70" :underline t))))
     (org-warning ((t (:foreground "#f43841"))))
     (outline-1 ((t (:foreground "#96a6c8"))))
     (outline-2 ((t (:foreground "#f4f4ff"))))
     (outline-3 ((t (:foreground "#ffdd33"))))
     (outline-4 ((t (:foreground "#cc8c3c"))))
     (outline-5 ((t (:foreground "#95a99f"))))
     (outline-6 ((t (:foreground "#95a99f"))))
     (outline-7 ((t (:foreground "#ffdd33"))))
     (outline-8 ((t (:foreground "#73c936"))))
     (py-XXX-tag-face ((t (:foreground "#cc8c3c"))))
     (py-builtins-face ((t (:foreground "#ffdd33"))))
     (py-class-name-face ((t (:foreground "#95a99f"))))
     (py-decorators-face ((t (:foreground "#ffdd33"))))
     (py-exception-name-face ((t (:foreground "#ffdd33"))))
     (py-pseudo-keyword-face ((t (:foreground "#ffdd33"))))
     (query-replace ((t (:foreground "#000" :background "#f5f5f5"))))
     (region ((t (nil))))
     (rng-error ((t (:foreground "#f43841"))))
     (rngalt-validation-header-bottom ((t (:background "RGB:87/CE/FA" :foreground "white"))))
     (rngalt-validation-header-top ((t (:background "white" :foreground "RGB:87/CE/FA"))))
     (rst-level-1-face ((t (:background "grey15"))))
     (rst-level-2-face ((t (:background "grey25"))))
     (rst-level-3-face ((t (:background "grey35"))))
     (rst-level-4-face ((t (:background "grey40"))))
     (rst-level-5-face ((t (:background "grey50"))))
     (rst-level-6-face ((t (:background "grey60"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "#484951" :foreground "#F4F4FF"))))
     (sgml-namespace ((t (:foreground "#ffdd33"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-match-face ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "#52494e" :foreground "#fff"))))
     (trailing-whitespace ((t (:background "#f43841" :foreground "#000"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (web-vcs-gold ((t (:background "gold" :foreground "black"))))
     (web-vcs-green ((t (:background "#8f6" :foreground "black"))))
     (web-vcs-mode-line ((t (:background "OrangeRed" :foreground "black"))))
     (web-vcs-mode-line-inactive ((t (:background "Orange" :foreground "black"))))
     (web-vcs-pink ((t (:background "pink" :foreground "black"))))
     (web-vcs-red ((t (:background "#f86" :foreground "black"))))
     (web-vcs-yellow ((t (:background "yellow" :foreground "black"))))
     (which-func ((t (:foreground "Blue1"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray")))))))
(add-to-list 'color-themes '(my-color-theme  "Matt's color theme" "Matt Patey"))